# Generated by Django 2.2.7 on 2019-11-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=70)),
                ('service_type', models.CharField(choices=[('CCA_AMERICAS', 'hey'), ('CCA_APAC', 'hey1'), ('CCA_EMEA', 'hey3')], max_length=30)),
            ],
        ),
    ]
