# Generated by Django 2.2.7 on 2019-11-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='service_type',
            field=models.CharField(choices=[('router1', 'Router'), ('router2', 'Router+'), ('router2', 'Router++')], max_length=30),
        ),
    ]
