# Generated by Django 3.0.2 on 2020-02-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statool', '0002_auto_20191120_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='service_type',
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('router', 'Router'), ('switch', 'Switch'), ('firewall', 'Firewall')], default='000000', max_length=30),
        ),
        migrations.AddField(
            model_name='device',
            name='host',
            field=models.CharField(default='000000', max_length=70),
        ),
        migrations.AddField(
            model_name='device',
            name='platform',
            field=models.CharField(choices=[('cisco', 'ios'), ('junos', 'junos')], default='Firewall', max_length=30),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
