# Generated by Django 3.0.2 on 2020-04-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statool', '0003_auto_20200204_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='platform',
            field=models.CharField(choices=[('cisco', 'ios'), ('juniper', 'junos')], default='Firewall', max_length=30),
        ),
    ]
