# Generated by Django 3.0.2 on 2020-04-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statool', '0004_auto_20200405_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('host', models.CharField(default='000000', max_length=70)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=70)),
                ('device_type', models.CharField(choices=[('router', 'Router'), ('switch', 'Switch'), ('firewall', 'Firewall')], default='000000', max_length=30)),
                ('platform', models.CharField(choices=[('cisco', 'ios'), ('juniper', 'junos')], default='Firewall', max_length=30)),
            ],
        ),
    ]
