# Generated by Django 3.0.2 on 2020-04-06 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statool', '0005_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='service',
            name='host',
        ),
        migrations.RemoveField(
            model_name='service',
            name='password',
        ),
        migrations.RemoveField(
            model_name='service',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='service',
            name='username',
        ),
    ]
