# Generated by Django 3.0.2 on 2020-05-05 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statool', '0006_auto_20200406_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='devices',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='statool.Device'),
        ),
    ]
