# Generated by Django 3.0.2 on 2020-05-05 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statool', '0007_service_devices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='devices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='statool.Device'),
        ),
    ]
